version: '3.4'

services:
  einvoice.hungary.api:
    image: ${DOCKER_REGISTRY-}einvoicehungaryapi
    build:
      context: .
      dockerfile: src/eInvoice.Hungary.Api/Dockerfile
    depends_on:
      - rabbitmq
      - sql.data
      - mongo
  
  rabbitmq:
    image: rabbitmq:3.7.23-management-alpine

  sql.data:
    hostname: sql-test
    image: microsoft/mssql-server-linux:2017-latest

  mongo-express:
    image: mongo-express
    links:
      - mongo
    networks:
      - mongo-compose-network

  mongo:
    image: mongo
    networks:
      - mongo-compose-network

networks: 
    mongo-compose-network:
      driver: bridge