// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eInvoice.Hungary.Infrastructure.WriteModel.Context;

namespace eInvoice.Hungary.Infrastructure.Migrations
{
    [DbContext(typeof(SqlContext))]
    [Migration("20200830221702_InvoiceHistory_Update")]
    partial class InvoiceHistory_Update
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("eInvoice.Hungary.Domain.AggregatesModel.InvoiceAggregate.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyCode")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<Guid?>("CurrentInvoiceDataId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenceId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("eInvoice.Hungary.Domain.AggregatesModel.InvoiceAggregate.InvoiceDataReference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InvoiceDataId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("InvoiceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoiceDataReference");
                });

            modelBuilder.Entity("eInvoice.Hungary.Domain.AggregatesModel.InvoiceAggregate.InvoiceHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InvoiceDataReferenceId")
                        .HasColumnType("int");

                    b.Property<int?>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceDataReferenceId");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoiceHistory");
                });

            modelBuilder.Entity("eInvoice.Hungary.Domain.AggregatesModel.InvoiceAggregate.InvoiceDataReference", b =>
                {
                    b.HasOne("eInvoice.Hungary.Domain.AggregatesModel.InvoiceAggregate.Invoice", "Invoice")
                        .WithMany("InvoiceDataReference")
                        .HasForeignKey("InvoiceId");
                });

            modelBuilder.Entity("eInvoice.Hungary.Domain.AggregatesModel.InvoiceAggregate.InvoiceHistory", b =>
                {
                    b.HasOne("eInvoice.Hungary.Domain.AggregatesModel.InvoiceAggregate.InvoiceDataReference", "InvoiceDataReference")
                        .WithMany()
                        .HasForeignKey("InvoiceDataReferenceId");

                    b.HasOne("eInvoice.Hungary.Domain.AggregatesModel.InvoiceAggregate.Invoice", "Invoice")
                        .WithMany("History")
                        .HasForeignKey("InvoiceId");
                });
#pragma warning restore 612, 618
        }
    }
}
